# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify
fail_fast: false

default_language_version:
  python: python3.13

repos:
  - repo: local
    hooks:
      - id: format
        name: ruff-format
        language: system
        types: [python]
        entry: uv run ruff format
      - id: checks
        name: ruff-check
        language: system
        types: [python]
        entry: uv run ruff check
