"""initial migrations

Revision ID: f6185caa4512
Revises: 
Create Date: 2025-05-17 18:08:54.402722+00:00

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6185caa4512'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('NULL', 'IN_PROGRESS', 'COMPLETED', 'ERROR', name='taskstatus', schema='processing'), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='processing'
    )
    op.create_index(op.f('ix_processing_task_survey_id'), 'task', ['survey_id'], unique=False, schema='processing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_task_survey_id'), table_name='task', schema='processing')
    op.drop_table('task', schema='processing')
    # ### end Alembic commands ###
