name: FormulAI CI

on:
  pull_request:

jobs:
  detect-changes:
    name: Detect changed paths
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      processing: ${{ steps.filter.outputs.processing }}
      survey: ${{ steps.filter.outputs.survey }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
            processing:
              - 'processing/**'
            survey:
              - 'survey/**'

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run dev &
      - run: npx wait-on http://localhost:5173
      - run: npm run test:e2e

  processing-tests:
    name: Processing Service Tests
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.processing == 'true'
    defaults:
      run:
        working-directory: processing
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv and ruff
        run: |
          pip install uv
          pip install ruff
      - name: Sync dependencies
        run: uv sync
      - name: Run lint ruff
        run: ruff check .
      - name: Run tests
        run: uv run pytest

  survey-tests:
    name: Survey Service Tests
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.survey == 'true'
    defaults:
      run:
        working-directory: survey
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run lint (Checkstyle)
        run: ./mvnw checkstyle:check
      - name: Run tests
        run: ./mvnw clean verify jacoco:report
      - name: Check coverage >= 80%
        run: ./mvnw jacoco:check
