ame: Survey Service Tests

on:
  pull_request:
    paths:
      - 'survey/**'

jobs:
  survey-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: survey
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run lint (Checkstyle)
        run: ./mvnw checkstyle:check
      - name: Run tests
        run: ./mvnw clean verify jacoco:report
      - name: Check coverage >= 80%
        run: ./mvnw jacoco:check        